name: CD Fake
on: 
    workflow_dispatch: 
jobs:
    deploy-fake-homolog:
        runs-on: ubuntu-latest
        environment:
            name: homologacao
            url: "http://homolocao.com.br"
        steps:
            - name: Fake de deploy em ambiente
            - run: echo "Deploy no ambiente ${vars.AMBIENTE_DEPLOY }}"
              
    
    test-fake:
        runs-on: ubuntu-latest
        environment:
            name: homologacao
            url: "http://homolocao.com.br"
        needs: [deploy-fake]
        steps:
            - name: Fake de teste em ambiente
            - run: echo "Test no ambiente ${vars.AMBIENTE_DEPLOY }}"
    
    deploy-fake-producao:
        runs-on: ubuntu-latest
        environment:
            name: producao
            url: "http://producao.com.br"
        needs: [test-fake]
        steps:
            - name: Fake de deploy em ambiente
            - run: echo "Deploy no ambiente ${vars.AMBIENTE_DEPLOY }}"
