name: CD Fake
on: 
    workflow_dispatch: 
jobs:
    deploy-fake-homologacao:
        runs-on: ubuntu-latest
        environment: homologacao
        steps:
            - name: Fake de deploy em ambiente
              url: "http://homolocao.com.br"
    
    test-fake:
        runs-on: ubuntu-latest
        environment: homologacao
        needs: deploy-fake
        steps:
            - name: Fake de teste em ambiente
              url: "http://homolocao.com.br"
    
    deploy-fake-producao:
        runs-on: ubuntu-latest
        environment: producao
        needs: test-fake
        steps:
            - name: Fake de deploy em ambiente
              url: "http://producao.com.br"
